# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170628_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Author')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(verbose_name='Enter the ISBN Number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(verbose_name='Summary of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title of the Book'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the publiation'),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='books.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='publication',
            field=models.ManyToManyField(to='books.Publication'),
        ),
    ]
