# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170628_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='publication',
            new_name='publications',
        ),
    ]
